name       : libexempi
version    : 2.4.5
release    : 7
source     :
    - https://libopenraw.freedesktop.org/download/exempi-2.4.5.tar.bz2 : 406185feb88e84ea1d4b4251370be2991205790d7113a7e28e192ff46a4f221e
homepage   : http://libopenraw.freedesktop.org/wiki/Exempi/
license    :
    - LGPL-2.1
    - BSD-2-Clause
summary    : Exempi is an implementation of XMP (Adobe's Extensible Metadata Platform).
component  : desktop.library
builddeps  :
    - libboost-devel
optimize   :
    - lto
description: |
    Exempi is an implementation of XMP (Adobe's Extensible Metadata Platform).
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
