name       : libexempi
version    : 2.6.3
release    : 12
source     :
    - https://libopenraw.freedesktop.org/download/exempi-2.6.3.tar.bz2 : b0749db18a9e78cf771737954a838cdcdb1d5415888bac1ba9caf8cba77c656c
homepage   : https://libopenraw.freedesktop.org/wiki/Exempi/
license    : BSD-3-Clause
component  : desktop.library
summary    : Exempi is an implementation of XMP (Adobe's Extensible Metadata Platform)
description: |
    Exempi is an implementation of XMP (Adobe's Extensible Metadata Platform).
optimize   :
    - lto
builddeps  :
    - libboost-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
