name       : libexempi
version    : 2.4.4
release    : 6
source     :
    - https://libopenraw.freedesktop.org/download/exempi-2.4.4.tar.bz2 : a2d59a9c5d449d88480dc9ffb3220f34b9789367dbe6fdc957ed2b9a78ec3db0
homepage   : http://libopenraw.freedesktop.org/wiki/Exempi/
license    :
    - LGPL-2.1
    - BSD-2-Clause
summary    : Exempi is an implementation of XMP (Adobe's Extensible Metadata Platform).
component  : desktop.library
builddeps  :
    - libboost-devel
optimize   :
    - lto
description: |
    Exempi is an implementation of XMP (Adobe's Extensible Metadata Platform).
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
