name       : libexempi
version    : 2.6.1
release    : 10
source     :
    - https://libopenraw.freedesktop.org/download/exempi-2.6.1.tar.bz2 : 072451ac1e0dc97ed69a2e5bfc235fd94fe093d837f65584d0e3581af5db18cd
homepage   : https://libopenraw.freedesktop.org/wiki/Exempi/
license    : BSD-3-Clause
component  : desktop.library
summary    : Exempi is an implementation of XMP (Adobe's Extensible Metadata Platform)
description: |
    Exempi is an implementation of XMP (Adobe's Extensible Metadata Platform).
optimize   :
    - lto
builddeps  :
    - libboost-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
